openapi: 3.1.0
info:
  version: 1.0.0
  title: University
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of university app
servers:
  - url: http://127.0.0.1:9090
tags:
  - name: Students
    description: Operation with students.
paths:
  /api/students/{id}:
    get:
      $ref: ../swagger/paths/students/{id}/get.yaml
  /api/students:
    post:
      $ref: ../swagger/paths/students/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
